Repository Caleydo/ordino_public, pull requests merged in 2020-03, with the labels that each got.

#53 Activate `"downlevelIteration": true` in tsconfig.json
  tsconfig.json
Labels: release: minor

#50 Update to Typescript 3.8
  package.json
Labels: priority: high, release: major, type: refactor

#54 Update dependencies
  package.json
Labels: dependencies, priority: medium, type: refactor

#56 Change `buildId` to `JSON.stringify(buildId)`
  webpack.config.js
Labels: priority: medium, type: refactor

#57 Release 7.0.0
  .github/CODEOWNERS
  package.json
  tsconfig.json
  webpack.config.js
Labels: release: major

#46 Migrate to jest for testing
  .circleci/config.yml
  jest.config.js
  karma.conf.js
  package.json
  tsd.d.ts
  tslint.json
  webpack.config.js
Labels: release: major, type: refactor
