Repository Caleydo/ordino_public, pull requests merged in 2020-07, with the labels that each got.

#64 Show Ordino Public migration message for persistent sessions in start menu
  src/WelcomeView.ts
Labels: release: minor

#66 Fix width of migration message in welcome view
  src/welcome_view.html
Labels: release: patch

#67 Use localStorage for migration popup
  src/WelcomeView.ts
Labels: release: patch, type: bug

#68 Move deploy files from app to product
  deploy/Dockerfile
  deploy/nginx-default.conf
Labels: priority: high, type: refactor
