Repository Caleydo/ordino_public, pull requests merged in 2021-06, with the labels that each got.

#105 Update content and minor fixes
  dist/pages/DatasetsPage.js
  dist/pages/DatasetsPage.js.map
  dist/pages/FeaturesPage.js
  dist/pages/FeaturesPage.js.map
  dist/pages/HelpPage.js
  dist/pages/NewsPage.js
  dist/pages/NewsPage.js.map
  dist/pages/PublicationPage.js
  dist/pages/PublicationPage.js.map
  dist/pages/components/DevelopedByAffiliations.js
  dist/pages/components/DisclaimerCard.js
  dist/pages/components/DisclaimerCard.js.map
  dist/pages/components/FeatureCard.js
  dist/pages/components/OrdinoContactForm.js
  dist/pages/components/OrdinoContactForm.js.map
  dist/pages/components/OrdinoHelpSection.js
  dist/pages/components/OrdinoHelpSection.js.map
  dist/pages/components/OrdinoHero.js
  dist/pages/components/OrdinoHero.js.map
  dist/pages/components/OrdinoTeaserCards.js
  dist/pages/components/OrdinoTeaserCards.js.map
  dist/pages/components/SourceCodeCard.js
  dist/pages/components/SourceCodeCard.js.map
  dist/pages/components/TermsOfUseCard.js
  dist/pages/components/TermsOfUseCard.js.map
  dist/pages/components/VideoCard.js
  dist/pages/components/VideoCard.js.map
  dist/scss/pages/pages.scss
  src/pages/DatasetsPage.tsx
  src/pages/FeaturesPage.tsx
  src/pages/HelpPage.tsx
  src/pages/NewsPage.tsx
  src/pages/PublicationPage.tsx
  src/pages/components/DevelopedByAffiliations.tsx
  src/pages/components/DisclaimerCard.tsx
  src/pages/components/FeatureCard.tsx
  src/pages/components/OrdinoContactForm.tsx
  src/pages/components/OrdinoHelpSection.tsx
  src/pages/components/OrdinoHero.tsx
  src/pages/components/OrdinoTeaserCards.tsx
  src/pages/components/SourceCodeCard.tsx
  src/pages/components/TermsOfUseCard.tsx
  src/pages/components/VideoCard.tsx
  src/scss/pages/pages.scss
Labels: release: minor, type: refactor

#106 Remove welcome.scss
  .yo-rc.json
  dist/scss/main.scss
  dist/scss/pages/base/_base.scss
  src/scss/main.scss
  src/scss/pages/base/_base.scss
Labels: type: deployment

#107 Integrate feedback on the features page
  dist/pages/FeaturesPage.js
  dist/pages/FeaturesPage.js.map
  src/pages/FeaturesPage.tsx
Labels: release: minor, type: refactor

#108 Use `ToursSection` and `TourCard` on `ToursPage`
  dist/pages/ToursPage.js
  dist/pages/ToursPage.js.map
  src/pages/ToursPage.tsx
Labels: type: refactor

#110 Redirect old session links to app subdirectory
  dist/initialize.welcome.js
  dist/initialize.welcome.js.map
  src/initialize.welcome.tsx
Labels: release: minor, type: feature

#111 Update news in Ordino teaser card
  dist/pages/NewsPage.js
  dist/pages/NewsPage.js.map
  dist/pages/components/OrdinoTeaserCards.js
  dist/pages/components/OrdinoTeaserCards.js.map
  src/pages/NewsPage.tsx
  src/pages/components/OrdinoTeaserCards.tsx
Labels: release: minor, type: feature
