Repository Caleydo/ordino_public, pull requests merged in 2021-08, with the labels that each got.

#113 Hide clue mode buttons
  dist/initialize.app.js
  dist/initialize.app.js.map
  src/initialize.app.ts
Labels: type: feature, release: minor

#116 Update Ordino video
  dist/pages/PublicationPage.js
  dist/pages/components/OrdinoHero.js
  dist/pages/components/OrdinoHero.js.map
  dist/pages/components/VideoCard.js
  src/pages/PublicationPage.tsx
  src/pages/components/OrdinoHero.tsx
  src/pages/components/VideoCard.tsx
Labels: type: refactor

#118 Fix modal close button for OrdinoHero video
  dist/pages/components/OrdinoHero.js
  dist/pages/components/OrdinoHero.js.map
  src/pages/components/OrdinoHero.tsx
Labels: release: patch
