Repository Caleydo/ordino_public, pull requests merged in 2021-05, with the labels that each got.

#91 Change "Learn more about Ordino" to link to help page
  dist/pages/ToursPage.js
  dist/pages/ToursPage.js.map
  dist/pages/components/OrdinoHero.js
  dist/pages/components/OrdinoHero.js.map
  src/pages/ToursPage.tsx
  src/pages/components/OrdinoHero.tsx
Labels: release: minor, type: refactor

#90 Adapt header as the figma prototype
  dist/initialize.app.js
  dist/initialize.app.js.map
  src/initialize.app.ts
Labels: release: minor, type: refactor

#92 Help page: add links to other pages
  dist/pages/components/VideoCard.d.ts
  dist/pages/components/VideoCard.js
  dist/pages/components/VideoCard.js.map
  src/pages/components/VideoCard.tsx
Labels: release: minor, type: feature

#94 Improve text and markup for the Terms of Use card
  dist/pages/HelpPage.js
  dist/pages/HelpPage.js.map
  src/pages/HelpPage.tsx
Labels: release: minor, type: refactor

#93 Add contact form logic
  dist/pages/components/OrdinoContactForm.js
  dist/pages/components/OrdinoContactForm.js.map
  src/pages/components/OrdinoContactForm.tsx
Labels: release: minor, type: feature

#96 Replace `react-bootstrap` with plain Bootstrap
  dist/pages/DatasetsPage.js
  dist/pages/DatasetsPage.js.map
  dist/pages/FeaturesPage.js
  dist/pages/FeaturesPage.js.map
  dist/pages/HelpPage.js
  dist/pages/HelpPage.js.map
  dist/pages/NewsPage.js
  dist/pages/NewsPage.js.map
  dist/pages/PublicationPage.js
  dist/pages/PublicationPage.js.map
  dist/pages/ToursPage.js
  dist/pages/ToursPage.js.map
  dist/pages/components/DisclaimerCard.js
  dist/pages/components/DisclaimerCard.js.map
  dist/pages/components/FeatureCard.js
  dist/pages/components/FeatureCard.js.map
  dist/pages/components/GettingStarted.js
  dist/pages/components/GettingStarted.js.map
  dist/pages/components/OrdinoContactForm.js
  dist/pages/components/OrdinoContactForm.js.map
  dist/pages/components/OrdinoHero.js
  dist/pages/components/OrdinoHero.js.map
  dist/pages/components/OrdinoTeaserCards.js
  dist/pages/components/OrdinoTeaserCards.js.map
  dist/pages/components/VideoCard.js
  dist/pages/components/VideoCard.js.map
  src/pages/DatasetsPage.tsx
  src/pages/FeaturesPage.tsx
  src/pages/HelpPage.tsx
  src/pages/NewsPage.tsx
  src/pages/PublicationPage.tsx
  src/pages/ToursPage.tsx
  src/pages/components/DisclaimerCard.tsx
  src/pages/components/FeatureCard.tsx
  src/pages/components/GettingStarted.tsx
  src/pages/components/OrdinoContactForm.tsx
  src/pages/components/OrdinoHero.tsx
  src/pages/components/OrdinoTeaserCards.tsx
  src/pages/components/VideoCard.tsx
Labels: type: refactor

#95 Register HelpTab to the start menu tabs
  dist/menu/HelpTab.d.ts
  dist/menu/HelpTab.js
  dist/menu/HelpTab.js.map
  dist/pages/components/OrdinoHelpSection.d.ts
  dist/pages/components/OrdinoHelpSection.js
  dist/pages/components/OrdinoHelpSection.js.map
  dist/phovea.js
  dist/phovea.js.map
  src/menu/HelpTab.tsx
  src/pages/HelpPage.tsx
  src/pages/components/OrdinoHelpSection.tsx
  src/phovea.ts
Labels: release: minor, type: feature, type: refactor

#97 Replace scrollspy on info pages with `OrdinoScrollSpy`
  dist/menu/HelpTab.js
  dist/menu/HelpTab.js.map
  dist/pages/HelpPage.js
  dist/pages/HelpPage.js.map
  dist/pages/NewsPage.js
  dist/pages/NewsPage.js.map
  dist/pages/components/OrdinoHelpSection.d.ts
  dist/pages/components/OrdinoHelpSection.js
  dist/pages/components/OrdinoHelpSection.js.map
  dist/pages/components/SourceCodeCard.d.ts
  dist/pages/components/SourceCodeCard.js
  dist/pages/components/SourceCodeCard.js.map
  dist/pages/components/TermsOfUseCard.d.ts
  dist/pages/components/TermsOfUseCard.js
  dist/pages/components/TermsOfUseCard.js.map
  dist/pages/components/VideoCard.d.ts
  dist/pages/components/VideoCard.js
  dist/pages/components/VideoCard.js.map
  dist/scss/components/VideoCard.scss
  dist/scss/main.scss
  dist/scss/pages/HelpPage.scss
  dist/scss/pages/main.scss
  dist/scss/pages/pages.scss
  package.json
  src/menu/HelpTab.tsx
  src/pages/HelpPage.tsx
  src/pages/NewsPage.tsx
  src/pages/components/OrdinoHelpSection.tsx
  src/pages/components/SourceCodeCard.tsx
  src/pages/components/TermsOfUseCard.tsx
  src/pages/components/VideoCard.tsx
  src/scss/components/VideoCard.scss
  src/scss/main.scss
  src/scss/pages/HelpPage.scss
  src/scss/pages/main.scss
  src/scss/pages/pages.scss
Labels: release: minor, type: refactor

#99 Update help page and jump to sections (slug)
  dist/initialize.welcome.js
  dist/initialize.welcome.js.map
  dist/pages/HelpPage.js
  dist/pages/HelpPage.js.map
  dist/pages/components/DisclaimerCard.js
  dist/pages/components/DisclaimerCard.js.map
  dist/pages/components/OrdinoHelpSection.js
  dist/pages/components/OrdinoHelpSection.js.map
  dist/pages/components/TermsOfUseCard.js
  dist/pages/components/TermsOfUseCard.js.map
  src/initialize.welcome.tsx
  src/pages/HelpPage.tsx
  src/pages/components/DisclaimerCard.tsx
  src/pages/components/OrdinoHelpSection.tsx
  src/pages/components/TermsOfUseCard.tsx
Labels: release: minor, type: feature

#98 Update content of the What's new page
  dist/assets/pages/annotation_column.png
  dist/assets/pages/data_download.png
  dist/assets/pages/gene_signature.jpg
  dist/assets/pages/tourdino.jpg
  dist/pages/NewsPage.js
  dist/pages/NewsPage.js.map
  src/assets/pages/annotation_column.png
  src/assets/pages/data_download.png
  src/assets/pages/gene_signature.jpg
  src/assets/pages/tourdino.jpg
  src/pages/NewsPage.tsx
Labels: release: minor, type: refactor

#100 Update text content of the Ordino `VideoCard`
  dist/pages/components/VideoCard.js
  dist/pages/components/VideoCard.js.map
  src/pages/components/VideoCard.tsx
Labels: release: minor, type: refactor

#101 Show correct version in welcome page
  dist/pages/components/OrdinoHelpSection.js
  dist/pages/components/SourceCodeCard.js
  dist/pages/components/SourceCodeCard.js.map
  src/pages/components/OrdinoHelpSection.tsx
  src/pages/components/SourceCodeCard.tsx
Labels: release: minor, type: bug

#102 Change hierarchy of the video card content
  dist/pages/components/VideoCard.js
  dist/pages/components/VideoCard.js.map
  src/pages/components/VideoCard.tsx
Labels: release: minor, type: refactor

#103 Update the design of the NewsPage
  dist/pages/NewsPage.js
  dist/pages/NewsPage.js.map
  src/pages/NewsPage.tsx
Labels: release: minor, type: refactor
